import { type NextPage } from "next";
import Head from "next/head";
import { GifList, ProfilePicture, Search } from "../components";
import { innerContainer, pageContainer } from "./styles.css";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Adim Giphy Demo</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={pageContainer}>
				<div className={innerContainer}>
					<ProfilePicture />
					<Search />
					<GifList />
				</div>
			</div>
		</>
	);
};

export default Home;
